### PR TITLE
CHANGELOG.md - use "# Changelog" format

### PR DESCRIPTION
**Pull request by nhosoi**
The auto-maintenance roles-tag-and-release.sh script adds the new
changelog next to the top "Changelog" title. To simplify the logic,
we'd like to have all CHANGELOG.md starting with "# Changelog".
Thanks!

### CODE REVIEW

**Comment by nhosoi** [comment]
Sadly, `actionshub/markdownlint@main` does not like the `#` format...?

**Comment by richm** [comment]
> Sadly, `actionshub/markdownlint@main` does not like the `#` format...?

Looks like it.  I guess that's why the network team chose the `========` style.   I guess we should use the `=====` style for all of the roles.

**Comment by nhosoi** [comment]
> > Sadly, `actionshub/markdownlint@main` does not like the `#` format...?
> 
> Looks like it. I guess that's why the network team chose the `========` style. I guess we should use the `=====` style for all of the roles.

Please note that the rule is specified in `network/.mdl_style.rb` as follows.
```
all
# https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md003---header-style
rule 'MD003', :style => :setext_with_atx
....
```

**Comment by richm** [comment]
> > > Sadly, `actionshub/markdownlint@main` does not like the `#` format...?
> > 
> > 
> > Looks like it. I guess that's why the network team chose the `========` style. I guess we should use the `=====` style for all of the roles.
> 
> Please note that the rule is specified in `network/.mdl_style.rb` as follows.
> 
> ```
> all
> # https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md003---header-style
> rule 'MD003', :style => :setext_with_atx
> ....
> ```

ok - then please change the rule to allow the `# Changelog` style

**Comment by nhosoi** [comment]
> > > > Sadly, `actionshub/markdownlint@main` does not like the `#` format...?
> > > 
> > > 
> > > Looks like it. I guess that's why the network team chose the `========` style. I guess we should use the `=====` style for all of the roles.
> > 
> > 
> > Please note that the rule is specified in `network/.mdl_style.rb` as follows.
> > ```
> > all
> > # https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md003---header-style
> > rule 'MD003', :style => :setext_with_atx
> > ....
> > ```
> 
> ok - then please change the rule to allow the `# Changelog` style

Unfortunately, the network's setup is the loosest one in MD003. That's why `### Bug fixes` can coexist with the underlined format.
https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md003---header-style
The setext_with_atx doc style allows atx-style headers of level 3 or more in documents with setext style headers:

I guess as long as using markdownlint, we cannot use `# Changelog`. :(

Closing this pr.

**Pull request closed without merging**
