### PR TITLE
Drop support for Ansible 2.8 by bumping the Ansible version to 2.9

### PR DESCRIPTION
**Pull request by spetrosi**
Bug 1989197 - drop support for Ansible 2.8
https://bugzilla.redhat.com/show_bug.cgi?id=1989197

### CODE REVIEW

**Comment by cathay4t** [comment]
@richm Please also remove test-harness for ansible 2.8 when you have time. Thank you!

**Review by cathay4t — APPROVED** [review]

**Comment by cathay4t** [comment]
@spetrosi Could you do [git signoff][1] of your commit?

[1]: https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for

**Comment by cathay4t** [comment]
Once this patch merged. We will do 1.4 release.

**Comment by richm** [comment]
Can we merge this PR?

**Pull request merged**
