### PR TITLE
add ansible-lint to github actions

### PR DESCRIPTION
**Pull request by richm**
Since we have disabled linting in molecule, use tox for running
ansible-lint.

### CODE REVIEW

**Comment by nhosoi** [comment]
Molecule fails in the `tox / python (3.6)` [result](https://github.com/linux-system-roles/network/pull/336/checks?check_run_id=1601866380). Could it be a config issue or a repo issue or ...?
`[91mError: Cannot find a valid baseurl for repo: base\\n\\x1b[0m', 'YumRepo Error: All mirror URLs are not using ftp, http[s] or file.\\n Eg. Invalid release/repo/arch combination/\\nremoving mirrorlist with no valid mirrors: /var/cache/yum/x86_64/6/base/mirrorlist.txt\\n', 'Removing intermediate container f565625394d3\\n']"}`

**Comment by richm** [comment]
>  [91mError: Cannot find a valid baseurl for repo: base\\n\\x1b[0m', 'YumRepo Error: All mirror URLs are not using ftp, http[s] or file.\\n Eg. Invalid release/repo/arch combination/\\nremoving mirrorlist with no valid mirrors: /var/cache/yum/x86_64/6/base/mirrorlist.txt\\n', 'Removing intermediate container f565625394d3\\n']"}

This is the next issue on my plate - what to do about centos6 support in molecule.

I would like to get rid of it as it is very difficult to continue to support, and we have integration CI test coverage on rhel6

**Comment by cathay4t** [comment]
@richm The `ansible-lint` is added to tox/py36 test, but that one is failed in CI. Could you take a look?

**Comment by richm** [comment]
> @richm The `ansible-lint` is added to tox/py36 test, but that one is failed in CI. Could you take a look?

It is a known failure - please ignore.  I'm working on a fix for it.

**Comment by richm** [comment]
> > @richm The `ansible-lint` is added to tox/py36 test, but that one is failed in CI. Could you take a look?
> 
> It is a known failure - please ignore. I'm working on a fix for it.

That is - it will require a separate PR to fix - but this PR needs to be merged first

**Review by nhosoi — APPROVED** [review]
lgtm

**Comment by cathay4t** [comment]
@richm I merged #341 before this one. Could rebase and resolved the conflict? Thank you!

**Comment by richm** [comment]
> @richm I merged #341 before this one. Could rebase and resolved the conflict? Thank you!

done

**Pull request merged**
