### PR TITLE
added optional route src parameter

### PR DESCRIPTION
**Pull request by h3po**
works with nm, untested with initscript
TODO: test with initscript
TODO: unit tests

Signed-off-by: h3po <mail@h3po.de>

### CODE REVIEW

**Comment by richm** [comment]
[citest]

**Comment by h3po** [comment]
> @h3po any updates?
I can't find the time to get myself familiar with the roles' testing framework. Just wanted to park the codechange here where it might be useful for someone

**Comment by otterdingo** [comment]
is there any news on this feature ? 
being unable to add src option on routing rule is an important lack for this ansible network configuration rôle.

**Comment by tyll** [comment]
@otterdingo I just stumbled by your comment by accident. Best would be (at this point) to file a BZ against RHEL/rhel-system-roles at https://bugzilla.redhat.com/ and provide a user story how you would be using the src option, then it will be more visible in our planning.

**Comment by h3po** [comment]
> > is there any news on this feature ? being unable to add src option on routing rule is an important lack for this ansible network configuration rôle.
> 
> @otterdingo Can you provide a user story that how you would benefit from this feature? Then we can move forward with our planning.

I'm using it for example on machines with multiple public ip addresses (multi-wan) in conjunction with custom routing tables

**Pull request closed without merging**
