### PR TITLE
ansible-lint: Fix ignore-errors failures

### PR DESCRIPTION
**Pull request by liangwen12year**
In some test playbooks, the `ignore_errors: true` can not be replaced by `changed_when: false`, because `changed_when` is not a valid attribute for a IncludeRole.

### CODE REVIEW

**Comment by liangwen12year** [comment]
[citest]

**Review by ffmancera — COMMENTED** [review]
I have been investigating this ansible-lint issue. According to docs:

```
This rule checks that playbooks do not use the ignore_errors directive to ignore all errors. Ignoring all errors in a playbook hides actual failures, incorrectly mark tasks as failed, and result in unexpected side effects and behavior.

Instead of using the ignore_errors: true directive, you should do the following:

* Ignore errors only when using the {{ ansible_check_mode }} variable.
* Use register to register errors.
* Use failed_when: and specify acceptable error conditions.
```

Using `failed_when: false` is a short cut to `ignore_errors: true` but it avoids ansible-lint warning. IMHO, this is a way to trick ansible-lint so it doesn't fail but it doesn't fix the warning detected by ansible-lint.

What do you think?

**Comment by richm** [comment]
> I have been investigating this ansible-lint issue. According to docs:
> 
> ```
> This rule checks that playbooks do not use the ignore_errors directive to ignore all errors. Ignoring all errors in a playbook hides actual failures, incorrectly mark tasks as failed, and result in unexpected side effects and behavior.
> 
> Instead of using the ignore_errors: true directive, you should do the following:
> 
> * Ignore errors only when using the {{ ansible_check_mode }} variable.
> * Use register to register errors.
> * Use failed_when: and specify acceptable error conditions.
> ```
> 
> Using `failed_when: false` is a short cut to `ignore_errors: true` but it avoids ansible-lint warning. IMHO, this is a way to trick ansible-lint so it doesn't fail but it doesn't fix the warning detected by ansible-lint.
> 
> What do you think?

If this were "runtime" code - that is, code run by end users in production - then yes, I would agree with you.  For tests code, it isn't that important to handle failures correctly - perhaps in a few cases, but in the vast majority of cases it is ok to ignore the errors.  We know it is mostly correct because this is the way it has been working in our testing for these past few years.  I say "mostly" because there are perhaps some cases where the test fails in a way that we do not expect, but so far those cases do not seem to alter the test results. (except maybe in the case of the bond tests which do sporadically fail . . .)

**Comment by liangwen12year** [comment]
[citest]

**Review by ffmancera — APPROVED** [review]
As I do not want to block on my nits, I will approve it. Thanks!

**Pull request merged**
