### PR TITLE
refactor: Use meaningful variable

### PR DESCRIPTION
**Pull request by liangwen12year**
Enhancement:
refractor: Use meaningful variable

Reason:
Some variables used in the module code are not meaningful at all, which mgiht be hard to read and understand. Therefore, replace them with meaningful variables.

Result:

Issue Tracker Tickets (Jira or BZ if any):

### CODE REVIEW

**Comment by liangwen12year** [comment]
[citest]

**Comment by liangwen12year** [comment]
[citest]

**Comment by liangwen12year** [comment]
[citest]

**Comment by liangwen12year** [comment]
[citest]

**Review by richm — APPROVED** [review]

**Pull request merged**
