### PR TITLE
Update README.md to note that network teaming is deprecated in RHEL 9

### PR DESCRIPTION
**Pull request by briansmith0**

### CODE REVIEW

**Comment by richm** [comment]
@briansmith0 you'll need to sign your commit - network role requires signed commits - probably the easiest way is to do `git commit --amend -s` then `git push -f ....`

**Comment by briansmith0** [comment]
@richm Sounds good, I just completed those steps.  Please let me know if this looks OK now or if there is anything else I need to do.  Thanks!

**Comment by richm** [comment]
> @richm Sounds good, I just completed those steps. Please let me know if this looks OK now or if there is anything else I need to do. Thanks!

hmm - there are now 2 commits - the first one is signed, the 2nd not

**Comment by briansmith0** [comment]
@richm  I'm not sure how to fix this at this point.  Could you reject/delete this PR and I can start over from scratch?

**Pull request closed without merging**
