### PR TITLE
ansible-lint: Fix command-instead-of-module failures

### PR DESCRIPTION
**Pull request by liangwen12year**

### CODE REVIEW

**Comment by liangwen12year** [comment]
[citest]

**Comment by liangwen12year** [comment]
[citest]

**Comment by ffmancera** [comment]
@liangwen12year there are some conflicts, could you resolve them?

**Comment by liangwen12year** [comment]
[citest]

**Comment by liangwen12year** [comment]
[citest]

**Review by ffmancera — APPROVED** [review]
LGTM!

**Pull request merged**
