### PR TITLE
[th/nm connection-type] fix creating vlan and mac profiles for NetworkManager

### LINKED ISSUE #19: MTU for vlan iface.
Hello,

I have setup a bond interface eg. bond0 and then I create a vlan on the bond0 eg. bond0.100, however the MTU for bond0 and its slave is correctly set to 9000, however I cannot set the MTU for the vlan interface and it defaults to 1500.

```
network_provider: nm
network_connections:
  # Bridge interface
  - name: br0
    state: up
    type: bridge
    interface_name: br0
    ip:
      dhcp4: no
      auto6: no
      gateway4: 1.0.0.1
      address:
        - "1.0.0.50/26"

  # Bond interface
  - name: bond0
    state: up
    type: bond
    interface_name: "bond0"
    bond:
      mode: 802.3ad
      miimon: 100
    mtu: 9000
    master: br0
    slave_type: bridge

  # Slave ethernet interfaces
  - name: em2
    state: up
    type: ethernet
    mtu: 9000
    interface_name: em2
    master: bond0

  - name: em1
    state: up
    type: ethernet
    mtu: 9000
    interface_name: em1
    master: bond0

  # VLAN on bond interface
  - name: bond0.100
    state: up
    type: vlan
    parent: bond0
    vlan_id: 100
    ip:
      address:
        - "10.10.10.51/24"
```

How can I solve this?

Thanks.

### PR DESCRIPTION
**Pull request by thom311**
Fixes #19

### CODE REVIEW

**Comment by tyll** [comment]
Awesome, thank you! Can you please run python-black once above the file to fix the CI errors?

**Comment by tyll** [comment]
This fixes the error reported in #19, however, there is another error:when also setting `state: up`:

vlan-mtu.yml:
```
---
- hosts: all
  vars:
    network_connections:
      - name: eth1
        type: ethernet
        autoconnect: no
        state: up
        mtu: 3000
        ip:
          dhcp4: no
          auto6: no

      - name: eth1.90
        parent: eth1
        type: vlan
        vlan_id: 90
        mtu: 2700
        state: up
        ip:
          dhcp4: no
          auto6: no

  tasks:
    - import_role:
        name: linux-system-roles.network
```

Errors:
```
 [WARNING]: [005] <info>  #0, state:up persistent_state:present, 'eth1': connection eth1, c9ca6b2c-0779-4026-899f-a3b53c0e3a89 already up to date

 [WARNING]: [006] <info>  #0, state:up persistent_state:present, 'eth1': up connection eth1, c9ca6b2c-0779-4026-899f-a3b53c0e3a89 skipped because already active

 [WARNING]: [007] <info>  #1, state:up persistent_state:present, 'eth1.90': update connection eth1.90, f6639067-2a2c-48ad-a2ac-e417dcc33ee6

 [WARNING]: [008] <info>  #1, state:up persistent_state:present, 'eth1.90': up connection eth1.90, f6639067-2a2c-48ad-a2ac-e417dcc33ee6 (is-modified)

 [WARNING]: [009] <error> #1, state:up persistent_state:present, 'eth1.90': up connection failed: failure to activate connection: nm-manager-error-quark: Failed to find a compatible device for this
connection (3)
```

`nmcli con down eth1.90; nmcli con up eth1.90` works, though.

**Comment by thom311** [comment]
>  [WARNING]: [009] <error> #1, state:up persistent_state:present, 'eth1.90': up connection failed: failure to activate connection: nm-manager-error-quark: Failed to find a compatible device for this
connection (3)

Dunno. This is a different issue than addressed by this pull-request. Please open a separate issue, with NM level=TRACE logs. Thanks.

**Comment by tyll** [comment]
[citest bad]

**Comment by tyll** [comment]
Thank you very much!

**Comment by pcahyna** [comment]
> This fixes the error reported in #19, however, there is another error:when also setting `state: up`:
> Errors:
> 
> ```
>  [WARNING]: [005] <info>  #0, state:up persistent_state:present, 'eth1': connection eth1, c9ca6b2c-0779-4026-899f-a3b53c0e3a89 already up to date
> 
>  [WARNING]: [006] <info>  #0, state:up persistent_state:present, 'eth1': up connection eth1, c9ca6b2c-0779-4026-899f-a3b53c0e3a89 skipped because already active
> 
>  [WARNING]: [007] <info>  #1, state:up persistent_state:present, 'eth1.90': update connection eth1.90, f6639067-2a2c-48ad-a2ac-e417dcc33ee6
> 
>  [WARNING]: [008] <info>  #1, state:up persistent_state:present, 'eth1.90': up connection eth1.90, f6639067-2a2c-48ad-a2ac-e417dcc33ee6 (is-modified)
> 
>  [WARNING]: [009] <error> #1, state:up persistent_state:present, 'eth1.90': up connection failed: failure to activate connection: nm-manager-error-quark: Failed to find a compatible device for this
> connection (3)
> ```
> 
> `nmcli con down eth1.90; nmcli con up eth1.90` works, though.

Has this been solved or at least analyzed?

**Comment by tyll** [comment]
> > This fixes the error reported in #19, however, there is another error:when also setting `state: up`:
> > Errors:
> > ```
> >  [WARNING]: [005] <info>  #0, state:up persistent_state:present, 'eth1': connection eth1, c9ca6b2c-0779-4026-899f-a3b53c0e3a89 already up to date
> > 
> >  [WARNING]: [006] <info>  #0, state:up persistent_state:present, 'eth1': up connection eth1, c9ca6b2c-0779-4026-899f-a3b53c0e3a89 skipped because already active
> > 
> >  [WARNING]: [007] <info>  #1, state:up persistent_state:present, 'eth1.90': update connection eth1.90, f6639067-2a2c-48ad-a2ac-e417dcc33ee6
> > 
> >  [WARNING]: [008] <info>  #1, state:up persistent_state:present, 'eth1.90': up connection eth1.90, f6639067-2a2c-48ad-a2ac-e417dcc33ee6 (is-modified)
> > 
> >  [WARNING]: [009] <error> #1, state:up persistent_state:present, 'eth1.90': up connection failed: failure to activate connection: nm-manager-error-quark: Failed to find a compatible device for this
> > connection (3)
> > ```
> > `nmcli con down eth1.90; nmcli con up eth1.90` works, though.
> 
> Has this been solved or at least analyzed?

I created #101 to track this. It has the NM logs as well.

**Comment by pcahyna** [comment]
Is there a test for the problem fixed?

**Pull request merged**
