### PR TITLE
Replace docker by podman in the installdeps

### PR DESCRIPTION
**Pull request by RMPR**

### CODE REVIEW

**Comment by tyll** [comment]
Why is this a good idea? What problem does it solve?

**Comment by richm** [comment]
> Why is this a good idea? What problem does it solve?

It solves the "problem" that we do not want to use docker except where strictly necessary - we want to use podman wherever possible.

**Comment by tyll** [comment]
> > Why is this a good idea? What problem does it solve?
> 
> It solves the "problem" that we do not want to use docker except where strictly necessary - we want to use podman wherever possible.

So changing the requirement makes molecule use podman instead of docker? It does not seem to me that it works this way. @RMPR Nevertheless, the justification needs to be added to the commit message. Please follow https://chris.beams.io/posts/git-commit

**Comment by RMPR** [comment]
I don't actually want this to be merged, I wanted to make the test fallback on podman if it's installed and docker no. See #165

**Comment by tyll** [comment]
> I don't actually want this to be merged, it is just an illustration of what I tried. See #165

Thank you for the clarification. There is no need to file a PR to show this. You can just point to your fork/commit in the issue. Also, if you do not want something to be merged, create it as a draft PR and mention this in the description.

**Comment by RMPR** [comment]
Okay, thanks for the pointers.

**Pull request closed without merging**
