### PR TITLE
Update formatting according to new black version

### PR DESCRIPTION
**Pull request by tyll**
Signed-off-by: Till Maas <opensource@till.name>

### CODE REVIEW

**Comment by pcahyna** [comment]
I thought that the benefit of Black was to provide consistent formatting, but if it is a moving target, it sort of nullifies this benefit.

**Comment by pcahyna** [comment]
what about freezing the version of Black that is used in the CI? We need to do it for ansible-lint anyway.

**Comment by tyll** [comment]
> I thought that the benefit of Black was to provide consistent formatting, but if it is a moving target, it sort of nullifies this benefit.

It is mostly consistent but since it is still under development, there might be some changes sometimes. It still provides the benefit that there are no discussions about the formatting.

> what about freezing the version of Black that is used in the CI? We need to do it for ansible-lint anyway.

I believe this will make it more annoying for the developers if different projects use different versions. Also, it rarely happens that it changes. Also, for ansible-lint it is just a temporary workaround.

**Comment by pcahyna** [comment]
> > what about freezing the version of Black that is used in the CI? We need to do it for ansible-lint anyway.
> 
> I believe this will make it more annoying for the developers if different projects use different versions. Also, it rarely happens that it changes. Also, for ansible-lint it is just a temporary workaround.

I believe it is a misunderstanding - IIUC from the discussion with @richm and @i386x we wanted to lock the version of ansible-lint permanently, so that it does not happen again that it suddenly starts complaining about something that used to be allowed and failing the CI runs. (The problem which triggered the discussion was not the bug that causes it to throw an exception, but the added check of role name which started failing on many roles.) Again, consistency and reproducibility of test results.

**Comment by richm** [comment]
> > > what about freezing the version of Black that is used in the CI? We need to do it for ansible-lint anyway.
> > 
> > 
> > I believe this will make it more annoying for the developers if different projects use different versions. Also, it rarely happens that it changes. Also, for ansible-lint it is just a temporary workaround.
> 
> I believe it is a misunderstanding - IIUC from the discussion with @richm and @i386x we wanted to lock the version of ansible-lint permanently, so that it does not happen again that it suddenly starts complaining about something that used to be allowed and failing the CI runs. (The problem which triggered the discussion was not the bug that causes it to throw an exception, but the added check of role name which started failing on many roles.) Again, consistency and reproducibility of test results.

We would like to lock the version of everything so we don't run into problems like this in the future (see molecule v2 -> v3 upgrade previously which broke molecule testing).  The problem is then - how will we know if it is safe to upgrade?  We would need CI for the CI - run a special version of CI that has no locked versions of anything - if that passes, we know it is safe to upgrade to whatever version was pulled when the unlocked versions were used.

The ansible-lint issue is a special case - why is it suddenly complaining about rolenames like `linux-system-roles.network`?  Are we going to have to rename `linux-system-roles` to something without `-`?  We know that we will have to do that when we build the Collections package, but do we have to do that for legacy role support?  I would think not, so then the next question is - is it ok to use the latest version of ansible-lint, but just add a global suppression for that rolename item?

As far as this particular instance of black - I think it is ok for the network role to update the formatting to conform to black, and not to lock the version of black.  We don't have a lot of roles which will be changing in the near future, so I don't expect them to get dinged by this black update issue.  If we do, we can evaluate if it will be expensive to reformat the python files - it is usually as easy as running black without the `--check --diff` arguments we use in tox.  Worst case, we can disable black for a particular repo using .travis/config.sh

**Comment by tyll** [comment]
> We would like to lock the version of everything so we don't run into problems like this in the future (see molecule v2 -> v3 upgrade previously which broke molecule testing). The problem is then - how will we know if it is safe to upgrade? We would need CI for the CI - run a special version of CI that has no locked versions of anything - if that passes, we know it is safe to upgrade to whatever version was pulled when the unlocked versions were used.

To me it seems that it is less effort to fix/lock this occasionally than to actively monitor and test all releases. @cathay4t @ffmancera what is your preference?

**Comment by pcahyna** [comment]
> The ansible-lint issue is a special case - why is it suddenly complaining about rolenames like linux-system-roles.network?

I don't think it is so special - issues with linters that will start complaining about something that used to be allowed will likely come up again and again.

> We don't have a lot of roles which will be changing in the near future, so I don't expect them to get dinged by this black update issue.

Doesn't the change in Black mean that every role that has any Python file, uses Black and there is Python code that is formatted differently using the new Black version will now fail in Travis CI? Maybe I misunderstood the impact.

**Comment by richm** [comment]
> > The ansible-lint issue is a special case - why is it suddenly complaining about rolenames like linux-system-roles.network?
> 
> I don't think it is so special - issues with linters that will start complaining about something that used to be allowed will likely come up again and again.
> 
> > We don't have a lot of roles which will be changing in the near future, so I don't expect them to get dinged by this black update issue.
> 
> Doesn't the change in Black mean that every role that has any Python file, uses Black and there is Python code that is formatted differently using the new Black version will now fail in Travis CI?

Yes, any role with python code will potentially fail Travis CI now.  But 1) except for network and storage, I don't think any of the roles that have python code will be changing any time soon 2) it may be that black doesn't complain because the role has formatted the code already to satisfy both the old and the new black formatting 3) storage has disabled black - .travis/config.sh has RUN_BLACK_DISABLED=true 4) it is pretty easy to have black automatically format the code

So we can probably handle these on a case-by-case basis as the need arises

> Maybe I misunderstood the impact.

**Comment by tyll** [comment]
> > We don't have a lot of roles which will be changing in the near future, so I don't expect them to get dinged by this black update issue.
> 
> Doesn't the change in Black mean that every role that has any Python file, uses Black and there is Python code that is formatted differently using the new Black version will now fail in Travis CI? Maybe I misunderstood the impact.

This depends on the change. If roles do not use the construct black is changing, they won't be affected.

**Comment by pcahyna** [comment]
> > > We don't have a lot of roles which will be changing in the near future, so I don't expect them to get dinged by this black update issue.
> > 
> > 
> > Doesn't the change in Black mean that every role that has any Python file, uses Black and there is Python code that is formatted differently using the new Black version will now fail in Travis CI? Maybe I misunderstood the impact.
> 
> This depends on the change. If roles do not use the construct black is changing, they won't be affected.

Sure. That's what I meant by "there is Python code that is formatted differently using the new Black version".

**Comment by tyll** [comment]
[citest bad]

**Pull request merged**
