### PR TITLE
Rectified and removed all the yamllint issues. 

### PR DESCRIPTION
**Pull request by NamanDh**
Still working on to see if there are any issues/bugs in the same

### CODE REVIEW

**Comment by NamanDh** [comment]
@tyll Please review this once

**Comment by tyll** [comment]
> @tyll Please review this once

- There are too many commits in this PR, please remove/squash commits like "created again"
- Please only address one issue per PR, if you want to migrate the bridges test properly name the PR and include only commits for this task. For other tasks, create appropriately PRs
- What yamllint issues are you fixing exactly? Please create an issue first so we can discuss the scope/idea. Currently it seems to be mostly unjustified changes.
- Please run the changed integration tests locally and report back that they worked or fix any open issue

Thank you

**Comment by richm** [comment]
Also, please rebase on top of the latest master branch.

**Comment by tyll** [comment]
Thank you for your contribution. Since there was no activity/response to my comment, I close this PR.

**Pull request closed without merging**
