### PR TITLE
molecule/tox: Support yamllint without molecule

### PR DESCRIPTION
**Pull request by tyll**
~~Update to the new molecule linter config. Also move the yamllint config
to the repo root directory to make it possible to use yamllint directly.~~
Changed it to only contain the yamllint config change and an update to tox to let it run yamllint.

### CODE REVIEW

**Comment by richm** [comment]
ok, but this means no molecule support for ansible 2.7 . . .

**Comment by tyll** [comment]
> ok, but this means no molecule support for ansible 2.7 . . .

I see, this could be a problem, so I removed the changes for molecule v3 but prepared the migration by keeping the yamllint config change.

**Comment by pcahyna** [comment]
@richm @i386x can this be done in the template?

**Comment by richm** [comment]
fedora-30 failure - not sure - some sort of urlopen error - hopefully transient network error
fedora-31 failure
```
TASK [linux-system-roles.network : Install packages] ***************************
task path: /tmp/tmphk9swdbe/tests/roles/linux-system-roles.network/tasks/main.yml:20
fatal: [/cache/Fedora-Cloud-Base-31-1.9.x86_64.qcow2]: FAILED! => {"changed": false, "msg": "Failed to download metadata for repo 'fedora-modular'", "rc": 1, "results": []}
	to retry, use: --limit @/tmp/tmphk9swdbe/tests/tests_states.retry
```
hopefully some sort of transient yum repo failure

**Comment by richm** [comment]
[citest bad]

**Comment by richm** [comment]
The fedora-30 tests are running incredibly slowly - the `TASK [linux-system-roles.network : Install packages]` step takes up to several minutes in some cases - I suspect there is a network issue or a problem with the fedora 30 yum repos.

**Comment by richm** [comment]
2020-03-24T01:52:39+0000: INFO: Finished in 2561 seconds task linux-system-roles/network/170:fedora-30: success

**Comment by richm** [comment]
2020-03-24T02:27:12+0000: INFO: Finished in 2069 seconds task linux-system-roles/network/170:fedora-31: success

**Comment by richm** [comment]
Definitely some sort of performance problems installing packages on Fedora

**Comment by tyll** [comment]
[citest bad]

**Comment by i386x** [comment]
> Definitely some sort of performance problems installing packages on Fedora

Yes, most of CI fails are of this type.

**Comment by i386x** [comment]
> @richm @i386x can this be done in the template?

Yes, I think this is good idea.

**Comment by richm** [comment]
> > @richm @i386x can this be done in the template?
> 
> Yes, I think this is good idea.

@tyll already did this - https://github.com/linux-system-roles/template/pull/15

**Pull request merged**
