### PR TITLE
Fix initscripts parameter names for declaring static ipv6 connections

### PR DESCRIPTION
**Pull request by jaedolph**

### CODE REVIEW

**Comment by jaedolph** [comment]
Addresses #310

**Comment by tyll** [comment]
Thank you, would it be possible for you to add an integration tests for static IPv6?

**Comment by jaedolph** [comment]
Yeah can do

**Comment by jaedolph** [comment]
Had some issues with RHEL8/Fedora not bringing the veth interface up during my new integration test. Seems to work if I put the veth peer in a network namespace, give it an ip and activate it though. Hope this isn't too hacky.

**Comment by cathay4t** [comment]
> Had some issues with RHEL8/Fedora not bringing the veth interface up during my new integration test. Seems to work if I put the veth peer in a network namespace, give it an ip and activate it though. Hope this isn't too hacky.

I have created PR fixing the test environment at https://github.com/linux-system-roles/network/pull/316 to fix your problem.

Could you pull the patch in locally and test again?

Thank you!

**Comment by jaedolph** [comment]
[citest bad]

**Comment by cathay4t** [comment]
@jaedolph I have merged the patch which should fixed the veth link issue. Can you remove the hack and rebase?

Thank you!

**Comment by jaedolph** [comment]
[citest bad]

**Comment by jharuda** [comment]
[citest]

**Comment by richm** [comment]
please rebase to latest `main` branch

**Comment by richm** [comment]
Is this a bug fix?  If so, could you add update the PR comment to explain what the bug is, and how this PR fixes it?

**Comment by tyll** [comment]
> Is this a bug fix? If so, could you add update the PR comment to explain what the bug is, and how this PR fixes it?

Yes, it is. I updated the commit message, linked the issue and rebased the branch.

**Comment by tyll** [comment]
@richm it seems that the code coverage statistics are not updated anymore, is this expected?

**Comment by richm** [comment]
> @richm it seems that the code coverage statistics are not updated anymore, is this expected?

Where are you expecting them to be updated?  I see https://coveralls.io/jobs/78099049

**Comment by tyll** [comment]
> > @richm it seems that the code coverage statistics are not updated anymore, is this expected?
> 
> Where are you expecting them to be updated? I see [coveralls.io/jobs/78099049](https://coveralls.io/jobs/78099049)

I expected a comment here like https://github.com/linux-system-roles/network/pull/311#issuecomment-718487089 and I believe that the comment was updated in the past.

**Comment by richm** [comment]
> > > @richm it seems that the code coverage statistics are not updated anymore, is this expected?
> > 
> > 
> > Where are you expecting them to be updated? I see [coveralls.io/jobs/78099049](https://coveralls.io/jobs/78099049)
> 
> I expected a comment here like [#311 (comment)](https://github.com/linux-system-roles/network/pull/311#issuecomment-718487089) and I believe that the comment was updated in the past.

I have no idea.  It is possible that when we switched from travis ci to github actions that stopped working.  Maybe the travis/github/coveralls integration is better than the travis/github/github actions integration?
I see that you are attempting to use the coveralls github action.  I had to do something similar in tox-lsr https://github.com/linux-system-roles/tox-lsr/blob/main/src/tox_lsr/test_scripts/runcoveralls.sh and https://github.com/linux-system-roles/tox-lsr/blob/main/src/tox_lsr/test_scripts/custom_coveralls.py uses some code from https://github.com/AndreMiras/coveralls-python-action

**Review by ffmancera — APPROVED** [review]
LGTM, thanks!

**Comment by tyll** [comment]
> I have no idea. It is possible that when we switched from travis ci to github actions that stopped working. Maybe the travis/github/coveralls integration is better than the travis/github/github actions integration?
> I see that you are attempting to use the coveralls github action. I had to do something similar in tox-lsr [https://github.com/linux-system-roles/tox-lsr/blob/main/src/tox_lsr/test_scripts/runcoveralls.sh](https://github.com/linux-system-roles/tox-lsr/blob/main/src/tox_lsr/test_scripts/runcoveralls.sh?rgh-link-date=2021-04-08T14%3A03%3A05Z) and [https://github.com/linux-system-roles/tox-lsr/blob/main/src/tox_lsr/test_scripts/custom_coveralls.py](https://github.com/linux-system-roles/tox-lsr/blob/main/src/tox_lsr/test_scripts/custom_coveralls.py?rgh-link-date=2021-04-08T14%3A03%3A05Z) uses some code from [AndreMiras/coveralls-python-action](https://github.com/AndreMiras/coveralls-python-action)

Hm, I assumed that Travis only pushed the data to coveralls and then coveralls takes care of the notification but then they might not have access to write comments.

Maybe it would also help to actually do the checks for the main branch as proposed in #380 - any reason push is currently missing there?

**Pull request merged**
