### PR TITLE
library: all the imports must be on the top

### PR DESCRIPTION
**Pull request by ffmancera**
According to PEP8 [1], the import are always put at the top of the file,
just after any module comments and docstrings, and before module globals
and constants.

Signed-off-by: Fernando Fernandez Mancera <ffmancera@riseup.net>

### CODE REVIEW

**Comment by ffmancera** [comment]
[citest commit:f15c5bf648e0c56f11f2003cb4f4555759def266]

**Comment by tyll** [comment]
[citest bad]

**Comment by tyll** [comment]
> [citest commit:f15c5bf648e0c56f11f2003cb4f4555759def266]

FYI: This is only needed for PRs from external contributors.

Are you planning to fix the import order for everything? Currently it is not checked by the CI because there are some special cases. It might be possible to ignore them individually and enable the check: https://github.com/linux-system-roles/network/blob/master/tox.ini#L186
https://github.com/linux-system-roles/network/blob/master/tox.ini#L186

**Comment by ffmancera** [comment]
> > [citest commit:f15c5bf648e0c56f11f2003cb4f4555759def266]
> 
> FYI: This is only needed for PRs from external contributors.
> 

Oh I didn't know that. Thanks!

> Are you planning to fix the import order for everything? Currently it is not checked by the CI because there are some special cases. It might be possible to ignore them individually and enable the check: https://github.com/linux-system-roles/network/blob/master/tox.ini#L186
> https://github.com/linux-system-roles/network/blob/master/tox.ini#L186

Yes it would be nice to do it for all the cases and ignore the exceptions individually. I think this improves the code readability. What do you think? Thanks!

**Comment by tyll** [comment]
> > Are you planning to fix the import order for everything? Currently it is not checked by the CI because there are some special cases. It might be possible to ignore them individually and enable the check: https://github.com/linux-system-roles/network/blob/master/tox.ini#L186
> > https://github.com/linux-system-roles/network/blob/master/tox.ini#L186
> 
> Yes it would be nice to do it for all the cases and ignore the exceptions individually. I think this improves the code readability. What do you think? Thanks!

Sure, in the long term it makes sense. Not sure how much effort it would be at this point. Would you like to take a look? If it is too much effort, I am fine with merging the PR as-is.

**Comment by ffmancera** [comment]
Rebased, thanks!

**Pull request merged**
