### PR TITLE
ansible-lint: Fix yaml[truthy] failures

### PR DESCRIPTION
**Pull request by liangwen12year**
Signed-off-by: Wen Liang <liangwen12year@gmail.com>

### CODE REVIEW

**Review by tyll — APPROVED** [review]
:+1: LGTM

**Review by tyll — CHANGES_REQUESTED** [review]
Actually, this also needs to remove the line to disable the truthy check: https://github.com/linux-system-roles/network/blob/main/.yamllint.yml#L55

The files will still not be tested because of https://github.com/linux-system-roles/network/blob/main/.ansible-lint#L22

**Comment by richm** [comment]
> Actually, this also needs to remove the line to disable the truthy check: https://github.com/linux-system-roles/network/blob/main/.yamllint.yml#L55
> 
> The files will still not be tested because of https://github.com/linux-system-roles/network/blob/main/.ansible-lint#L22

It will be tricky fixing the lint issues per-type because of this.  We can remove the `truthy: disable` as part of this PR, but we can't remove the `exclude_paths: - tests/` from .ansible-lint until we fix *all* of the ansible-lint issues.  That means we will be merging PRs that we can't yet test with ansible-lint, until we fix the last category of ansible-lint issues, at which point we will remove the `exclude_paths: - tests/` from .ansible-lint and find out if we got all of the issues.

Or, we go ahead and remove the `exclude_paths: - tests/` from .ansible-lint, and we have to manually verify that the PR did indeed fix all of the truthy issues, and we'll just have to live with the Ansible Lint check failures until all of the issues are fixed.

**Comment by tyll** [comment]
> > Actually, this also needs to remove the line to disable the truthy check: [`main`/.yamllint.yml#L55](https://github.com/linux-system-roles/network/blob/main/.yamllint.yml?rgh-link-date=2023-02-13T22%3A41%3A35Z#L55)
> > The files will still not be tested because of [`main`/.ansible-lint#L22](https://github.com/linux-system-roles/network/blob/main/.ansible-lint?rgh-link-date=2023-02-13T22%3A41%3A35Z#L22)
> 
> It will be tricky fixing the lint issues per-type because of this. We can remove the `truthy: disable` as part of this PR, but we can't remove the `exclude_paths: - tests/` from .ansible-lint until we fix _all_ of the ansible-lint issues. That means we will be merging PRs that we can't yet test with ansible-lint, until we fix the last category of ansible-lint issues, at which point we will remove the `exclude_paths: - tests/` from .ansible-lint and find out if we got all of the issues.

Removing the truthy:disable does not need to happen in this PR, strictly speaking, since it does not have any effect. Since its existence does not seem to be tracked, it seems to be the easiest thing to do.

> Or, we go ahead and remove the `exclude_paths: - tests/` from .ansible-lint, and we have to manually verify that the PR did indeed fix all of the truthy issues, and we'll just have to live with the Ansible Lint check failures until all of the issues are fixed.

Removing the exclusion of the tests directory with the last commit is fine. As long as the ansible-lint PRs are correct, it seems to be fine to accept that they might be incomplete and catch this at the end.

**Comment by ffmancera** [comment]
@liangwen12year The changes LGTM, but please check Till's comment. Thanks!

**Comment by tyll** [comment]
Actually, the truthy check needs to be enabled again to show that the non test files are correct. I added the necessary commit.

**Review by tyll — APPROVED** [review]

**Pull request merged**
