### PR TITLE
Only show stderr_lines by default

### PR DESCRIPTION
**Pull request by kwevers**
This avoids dumping all the parameters which can cause rather lengthy
output if multiple interfaces, routers, ... are configured.
The previous behaviour where all the params etc were displayed can
still be achieved by adding `-v` to the `ansible-playbook` command.

Resolves: #394

Signed-off-by: Kristof Wevers <kristof.wevers@infura.eu>

### CODE REVIEW

**Review by liangwen12year — APPROVED** [review]
Nice patch. LGTM.

**Comment by richm** [comment]
[citest commit:9b222c7b0e2abe13c5949ccfb007b217f7ede03c]

**Comment by tyll** [comment]
[citest bad]

**Review by cathay4t — APPROVED** [review]

**Comment by cathay4t** [comment]
Thanks for the effort! Merged.

**Pull request merged**
