### PR TITLE
feat: add AlmaLinux to RHEL compat distro list

### PR DESCRIPTION
**Pull request by betuxy**
Please add AlmaLinux to the list of distributions recognized as RHEL

### CODE REVIEW

**Comment by richm** [comment]
lgtm

**Review by liangwen12year — APPROVED** [review]

**Comment by richm** [comment]
> Please check the problems in `Commitlint / commit-checks` CI check.

I suggest adding "fix: " to the beginning of the commit and PR title

**Comment by richm** [comment]
still having problems - try setting the commit title and PR title to `fix: add AlmaLinux to RHEL compat distro list` - note the shortened length, and does not end with a full stop (i.e. a period character `.`)

**Comment by richm** [comment]
Thanks - lgtm - @liangwen12year ?  ready to merge?

**Comment by liangwen12year** [comment]
last time for Rocky Linux, we added it as the feature

I am thinking that instead of using `fix: add AlmaLinux to RHEL compat distro list`, can we use `feat: add AlmaLinux to RHEL compat distro list` ?

**Comment by betuxy** [comment]
@liangwen12year I renamed it to feat:

**Review by liangwen12year — APPROVED** [review]

**Pull request merged**
