### PR TITLE
On RHEL 7, enable epel using yum-config-manager

### PR DESCRIPTION
**Pull request by spetrosi**
Fixing the CI on RHEL 7, it was broken by PR #422

### CODE REVIEW

**Comment by tyll** [comment]
The commit needs to be signed-off, see the DCO CI failure.

**Comment by spetrosi** [comment]
I've signed the commit, the CI fails must be unrelated.

**Comment by richm** [comment]
[citest bad]

**Review by tyll — APPROVED** [review]
LGTM, thank you.

**Pull request merged**
