### PR TITLE
test: Clean up mock wifi at the end of each wireless test

### PR DESCRIPTION
**Pull request by liangwen12year**
Enhancement:

Reason:

Result:

Issue Tracker Tickets (Jira or BZ if any):

### CODE REVIEW

**Comment by liangwen12year** [comment]
[citest]

**Comment by liangwen12year** [comment]
I tested it locally, even if running qemu testing using `--make-batch`, I can only reproduce the `tests_wireless_wpa3_sae_nm.yml` (CentOS-Stream-8/ansible-2.9 ) failure. And the other test failures are caused by baseos ci testing environment, notably, there are two categories:

1.  control node lost the ssh connection to the managed host
```
Data could not be sent to remote host "10.31.43.169". Make sure this host can be reached over ssh: 
	to retry, use: --limit @/tmp/tests_bond_cloned_mac_initscripts.retry
```

2.  DNS problem
```
TASK [Install iproute] *********************************************************
task path: /WORKDIR/git-ci_fixslgi2sy4/tests/playbooks/tasks/manage_test_interface.yml:16
Tuesday 23 January 2024  19:48:22 +0000 (0:00:00.018)       0:00:03.363 ******* 
fatal: [sut]: FAILED! => {
    "changed": false,
    "rc": 1,
    "results": []
}

MSG:

Failed to download metadata for repo 'epel': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=epel-8&arch=x86_64&infra=stock&content=centos [Could not resolve host: mirrors.fedoraproject.org]
	to retry, use: --limit @/tmp/tests_route_device_initscripts.retry
```

**Comment by liangwen12year** [comment]
[citest]

**Comment by richm** [comment]
[citest bad]

**Pull request merged**
