### PR TITLE
Adding lacp_rate and xmit_hash_policy to bond

### PR DESCRIPTION
**Pull request by codeRhein**
Hello! Our division would like to contribute some of our developments for this project. Could you please take a look at this PR, which is adding more bonding support (`lacp_rate` and `xmit_hash_policy`). Thanks a lot !

### CODE REVIEW

**Comment by richm** [comment]
thanks
are these options specific to initscripts?  Is there an NetworkManager analogue for these settings?
We also require testing and documentation for these settings

**Comment by liangwen12year** [comment]
Notice that we already supported all the bonding options for the nm provider, IMHO, the feature support in initscipts backend was code freezed (we tend to only fix bugs there), is there a strong request for supporting the `lacp_rate` and `xmit_hash_policy` bond options to the initscripts provider ?

**Comment by codeRhein** [comment]
Hello, thanks so much for the pointers ! Yes I just noticed that these two options are supported for `NM` already, then I think there might be potential usage needs for initscripts, but there is no strong request at all. You can close this, thanks again !

**Comment by liangwen12year** [comment]
> Hello, thanks so much for the pointers ! Yes I just noticed that these two options are supported for `NM` already, then I think there might be potential usage needs for initscripts, but there is no strong request at all. You can close this, thanks again !

Hi, I am sorry for being discrouraging previously, if there is any potential usage for the initscripts provider based on your opinion,  let us keep your proposal and merge it when it is ready. 

Change requests:

1. Tox unit tests `tox -e black` failed, the problem is that the proposed python code is not wrapping around 88 characters, to fix it, you may use the command `black library/network_connections.py --line-length 88`

2. You may sign off the commit in order for the pr to pass the DCO test.

**Comment by codeRhein** [comment]
> > Hello, thanks so much for the pointers ! Yes I just noticed that these two options are supported for `NM` already, then I think there might be potential usage needs for initscripts, but there is no strong request at all. You can close this, thanks again !
> 
> Hi, I am sorry for being discrouraging previously, if there is any potential usage for the initscripts provider based on your opinion, let us keep your proposal and merge it when it is ready.
> 
> Change requests:
> 
> 1. Tox unit tests `tox -e black` failed, the problem is that the proposed python code is not wrapping around 88 characters, to fix it, you may use the command `black library/network_connections.py --line-length 88`
> 2. You may sign off the commit in order for the pr to pass the DCO test.

Thanks again !  No problem, I feel encouraged actually.  I communicated within our team, and it turns out that our system truly no longer requires these two options for `initscripts`.  So from our work perspective, this PR can be closed.  But of course, if you think this might help other users, please feel free to add it in future release. Thanks again for the pointers in change request, next time I will follow them when contributing 👍

**Comment by tyll** [comment]
> Thanks again ! No problem, I feel encouraged actually. I communicated within our team, and it turns out that our system truly no longer requires these two options for `initscripts`. So from our work perspective, this PR can be closed. But of course, if you think this might help other users, please feel free to add it in future release. Thanks again for the pointers in change request, next time I will follow them when contributing +1

Thank you. At this point I would like to wait for an actual user to request this who is also going to use it. Therefore I will close it until then.

**Pull request closed without merging**
