### PR TITLE
Remove workaround for host selection in ensure_provider_tests.py

### PR DESCRIPTION
**Pull request by liangwen12year**
Signed-off-by: Wen Liang <liangwen12year@gmail.com>

### CODE REVIEW

**Comment by tyll** [comment]
Thank you. Please check the CI results.

**Comment by liangwen12year** [comment]
> Thank you. Please check the CI results.
checked and updated the commit.

**Comment by tyll** [comment]
The commit message mentions "Remove workaround for host selection in ensure_provider_tests.py" but this does not remove the workaround but the comment that about it being a workaround but it is not considered a workaround anymore.

**Comment by liangwen12year** [comment]
> The commit message mentions "Remove workaround for host selection in ensure_provider_tests.py" but this does not remove the workaround but the comment that about it being a workaround but it is not considered a workaround anymore.

updated the commit message.

**Review by ffmancera — CHANGES_REQUESTED** [review]
I would like to suggest `Remove comment about host selection workaround` as a commit message, what do you think?

**Review by ffmancera — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
