### PR TITLE
Support creating and activating bond profiles in one run with initscripts

### LINKED ISSUE #242: bond creation from example does not work with initscipts
I've taken the example from https://github.com/linux-system-roles/network/blob/master/examples/bond_simple.yml

modified it to eth0, or any other device present in the system and executed it via 
ansible-playbook -vv -i localhost, bond_simple.yml

but it failed with network.service.

it looks slave profile is never created, as if I do so I can up bond via ifup

slave ifcfg
TYPE=Ethernet
DEVICE=eth0
ONBOOT=yes
MASTER=bond0
SLAVE=yes

### PR DESCRIPTION
**Pull request by tyll**
This fixes #242

### CODE REVIEW

**Comment by pcahyna** [comment]
Will this allow to specify bond masters/slaves in an arbitrary order in `network_connections`? Right now a particular (and I believe undocumented) order has been needed, otherwise the role failed.

**Comment by tyll** [comment]
> Will this allow to specify bond masters/slaves in an arbitrary order in `network_connections`? Right now a particular (and I believe undocumented) order has been needed, otherwise the role failed.

The profiles that are referenced in other profiles still need to be specified first.

**Comment by pcahyna** [comment]
This PR itself does not touch any tests. Does #241 add tests for it?

**Comment by tyll** [comment]
> This PR itself does not touch any tests. Does #241 add tests for it?

yes

**Pull request merged**
