### PR TITLE
use tox-lsr 2.2.1

### PR DESCRIPTION
**Pull request by nhosoi**
Upgrade to tox-lsr 2.2.1 to pick up fix for lock down the
version of ansible to ansible==2.10.* in tox-lsr.

### CODE REVIEW

**Review by richm — APPROVED** [review]

**Comment by richm** [comment]
@nhosoi network role requires signed commit - so do something like `git commit -s --amend` then `git push ...`

**Comment by nhosoi** [comment]
Oops. I did it again... :p Updating the commit...

**Comment by richm** [comment]
@tyll note that https://github.com/linux-system-roles/network/pull/362 will supersede this PR (if 362 is merged first)

**Comment by tyll** [comment]
Superseded by #362

**Pull request closed without merging**
