### PR TITLE
add infiniband support

### PR DESCRIPTION
**Pull request by thom311**
See also: https://bugzilla.redhat.com/show_bug.cgi?id=1470712

### CODE REVIEW

**Comment by hartsjc** [comment]
On remote node
```
# nmcli connection del ib0 enp5s0f0
Connection 'enp5s0f0' (de644003-5492-491f-a8b2-d80dc2ea9d4d) successfully deleted.
Connection 'ib0' (b9df9d0f-7c63-4469-afc6-4a7e8b4c48bf) successfully deleted.
```

Playbook
```
# cat network2.yml 
---
- hosts: host.domain.com
  vars:
    network_connections:
      - name: ib0
        state: absent
      - name: ib0
        interface_name: ib0
        type: infiniband
        state: up
        autoconnect: yes
        ip:
          dhcp4: no
          auto6: no
          address:
            - 10.0.0.5/30
  roles:
    - role: network-ib 
```


Run the playbook
```
# ansible-playbook -l host.domain.com network-ib.yml 
<snip>
TASK [network-ib : Configure networking connection profiles]  [WARNING]: <info>  #0, state:absent, "ib0": delete connection ib0, 0455bb02-1b72-49f1-875a-4a233daee6ff
 [WARNING]: <info>  #1, state:up, "ib0": add connection ib0, 0455bb02-1b72-49f1-875a-4a233daee6ff
 [WARNING]: <info>  #1, state:up, "ib0": up connection ib0, 0455bb02-1b72-49f1-875a-4a233daee6ff
changed: [host.domain.com]
TASK [network-ib : Re-test connectivity]
ok: [host.domain.com]
PLAY RECAP
host.domain.com              : ok=6    changed=1    unreachable=0    failed=0   
```

Of course still hitting following on about 1/2 runs when del/add method.
https://github.com/linux-system-roles/network/issues/7

But as for this change, positive results...
```
# nmcli connection 
NAME      UUID                                  TYPE            DEVICE   
enp5s0f0  057e249a-7e3c-44fb-b930-6a1bb1095df7  802-3-ethernet  enp5s0f0
ib0       0455bb02-1b72-49f1-875a-4a233daee6ff  infiniband      ib0
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by stefwalter** [comment]
@hartsjc @thom311 Are you able to change that test you posted above into an integration test? @larskarlitski Could help you. That integration test could become part of this pull request.

**Comment by thom311** [comment]
@stefwalter 

> Are you able to change that test you posted above into an integration test? 

integration tests would require that vagrant (or some test setup script) creates virtual interfaces to test the role.

I agree, CI tests should be greatly improved. Would be nice-to-have, or maybe even "essential". But they currently don't exist for existing interface types either. Such testing improvement should IMHO not block this pull request.

**Comment by larskarlitski** [comment]
> integration tests would require that vagrant (or some test setup script) creates virtual interfaces to test the role.

Can this be done from inside the running virtual machine or do we need to add a device through qemu? From a quick web search it looks like qemu cannot emulate infiniband devices (only pass-through), but I'm not very familiar with that topic.

> [...] Such testing improvement should IMHO not block this pull request.

I agree. If we can't come up with a solution this week, I'll merge the pull request as-is.

**Comment by hartsjc** [comment]
> Can this be done from inside the running virtual machine or do we need to add a device through qemu? From a quick web search it looks like qemu cannot emulate infiniband devices (only pass-through), but I'm not very familiar with that topic.

I am not aware of anyway to do it via emulation.  I happen to have bare-metal with them for other reasons and was able to test.

**Comment by larskarlitski** [comment]
> I am not aware of anyway to do it via emulation. I happen to have bare-metal with them for other reasons and was able to test.

Thanks for clarifying. Merging as-is, then.

**Pull request merged**
