### PR TITLE
add support to Rocky Linux

### PR DESCRIPTION
**Pull request by codeRhein**
Add support to Rocky Linux

### CODE REVIEW

**Comment by richm** [comment]
thanks!
The DCO test failed - this repo only accepts signed commits (e.g. git commit -s)
note that we don't have CI testing with Rocky, so we can't be sure if everything will work on Rocky

**Comment by liangwen12year** [comment]
If I understand it correctly, you only supported the Rocky Linux for initscripts provider, is there any user cases or user requests around this, if so, can you explain in the commit message?

**Comment by codeRhein** [comment]
Thanks again ! This is also similar to the previous PR I opened, there is no strong request from our side, we can close this as well, sorry for the noise, thanks !

**Comment by tyll** [comment]
@codeRhein if you sign off your commit as described in https://github.com/linux-system-roles/network/blob/main/contributing.md#sign-off-your-commit, then the PR is probably good to go.

**Comment by codeRhein** [comment]
> @codeRhein if you sign off your commit as described in https://github.com/linux-system-roles/network/blob/main/contributing.md#sign-off-your-commit, then the PR is probably good to go.

thanks so much! I should read more carefully about the contribution section, now it is signed. Thanks again!

**Review by tyll — APPROVED** [review]
:+1:

**Pull request merged**
