### PR TITLE
Update README.md to note that network teaming is deprecated in RHEL 9

### PR DESCRIPTION
**Pull request by briansmith0**

### CODE REVIEW

**Comment by briansmith0** [comment]
@richm  here is the new PR.  Please let me know if this one looks OK.  Thanks!

**Comment by richm** [comment]
> @richm here is the new PR. Please let me know if this one looks OK. Thanks!

The commit isn't signed, so the DCO check fails.  In addition, there is no explanatory commit message, although between the commit title and the actual change, the explanation is pretty obvious.

**Comment by briansmith0** [comment]
@richm Ok, I just tried it again.  Please let me know if this is now OK.  Thanks!

**Review by richm — APPROVED** [review]
lgtm

**Comment by liangwen12year** [comment]
Hi @briansmith0 , can you rebase the branch so that it is up-to-date with upstrean main ?

**Pull request merged**
